name: Release

on:
  push:
    branches:
      - '!**'
    tags:
      - '*'

jobs:
  release-libtsduck:
    runs-on: ubuntu-latest
    env:
      target: libtsduck-static
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository_owner }}/${{ env.target }}
          tags: |
            type=ref,event=tag
            type=match,pattern=v\d+
            type=match,pattern=v\d+\.\d+

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: ${{ env.target }}
          platforms: ${{ env.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  release-tsduck:
    needs: release-libtsduck
    runs-on: ubuntu-latest
    env:
      target: tsduck-static
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository_owner }}/${{ env.target }}
          tags: |
            type=ref,event=tag
            type=match,pattern=v\d+
            type=match,pattern=v\d+\.\d+

      - name: Set `libtsduck`
        id: libtsduck
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository_owner }}/libtsduck-static
          tags: type=ref,event=tag
          flavor: latest=false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: ${{ env.target }}
          platforms: ${{ env.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          build-args: libtsduck=${{ steps.libtsduck.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

env:
  platforms: linux/amd64, linux/386, linux/arm64, linux/arm/v7, linux/arm/v6
